### ISSUE TITLE
NXcomp_designer does not save changes

### ISSUE THREAD

**Issue by Ingvord** [jkotan/nexdatas.configtool#1]
To reproduce:

1. Load a component from a file
1. Make some changes, i.e. change field's type (all changes are applied, i.e. apply button is pressed)
1. Save... file is not updated

**Comment by jkotan** [comment]
Hi Igor,

Which version of the designer do you use?  Please try v1.6.7. It should fix the issue.

Bests,
Jan

**Comment by Ingvord** [comment]
Yes, this seems to be fixed now
